linters:
  enable:
    - gofmt
    - gci
    - goimports

  disable:
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - unparam

  presets:
  #  - bugs
  #  - comment
  #  - error
  #  - format
  #  - import
    - unused

run:
  timeout: 5m
