version: '3'

vars:
  PKG: "./..."
  FAILFAST: "-failfast"
  TIMEOUT: "1m"
  RUN: "''"

tasks:
  default:
    cmds:
      - task: lint
      - task: tests:local

  lint:
    cmds:
      - golangci-lint run -v --fix

  tests:
    cmds:
      - go test -race -coverpkg {{.PKG}} -coverprofile coverage.out {{.PKG}}
      - yaegi test .

  tests:local:
    cmds:
      - >
        go test -v {{.FAILFAST}} -race -coverpkg {{.PKG}} -coverprofile coverage.out
        -run {{.RUN}} -timeout {{.TIMEOUT}} {{.PKG}} |
        sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' |
        sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/'' |
        sed ''/RUN/s//$(printf "\033[34mRUN\033[0m")/''
      - yaegi test -v . |
        sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' |
        sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/'' |
        sed ''/RUN/s//$(printf "\033[34mRUN\033[0m")/''

  install:lint:
    cmds:
      - >
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
        sudo sh -s -- -b $(go env GOPATH)/bin latest

  install:yaegi:
    cmds:
      - >
        curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh |
        sudo bash -s -- -b $(go env GOPATH)/bin latest
