on:
  push:
    branches:
      - main
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  release:
    types: [ prereleased, released ]

name: Main
jobs:
  pr-style:
    if: github.event_name == 'pull_request'
    uses: formancehq/gh-workflows/.github/workflows/pr-style.yml@main

  lint:
    uses: formancehq/gh-workflows/.github/workflows/golang-lint.yml@main

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install task
        uses: arduino/setup-task@v1
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go mod vendor
      - name: Run tests
        run: task install:yaegi tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
